# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.22
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: Camptocamp
org_slug: camptocamp
rebel_module_groups:
- attachment_azure,cloud_platform_azure
repo_description: 'Tools to run Odoo on a cloud platform. Mainly Azure at the moment. '
repo_name: Odoo Cloud Addons
repo_slug: odoo-cloud-platform
repo_website: https://github.com/camptocamp/odoo-cloud-platform
use_pyproject_toml: true
use_ruff: true

